places = ["p1","ap2","p3","p4","p5"]
print(places)
print(sorted(places))
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort()
print(places)
